"""empty message

Revision ID: 237f4785f6dc
Revises: 
Create Date: 2024-12-08 21:29:53.934590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237f4785f6dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('alpha2', sa.String(length=2), nullable=True),
    sa.Column('alpha3', sa.String(length=3), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('countryCode', sa.String(length=2), nullable=False),
    sa.Column('isPublic', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('image', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('countryCode'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('countries')
    # ### end Alembic commands ###
